export const GAME_CONFIG = {
  BRICKS_ZONE_HEIGHT: 0.6,
  BRICKS_START_Y: 0.05,
  
  PADDLE_Y_POSITION: 0.9,
  PADDLE_WIDTH: 0.15,
  PADDLE_HEIGHT: 0.02,
  PADDLE_SPEED: 12,
  PADDLE_COLOR: 0x4A90E2,
  
  BALL_RADIUS: 8,
  BALL_SPEED: 10,
  BALL_COLOR: 0xFFFFFF,
  BALL_START_Y: 0.7,
  
  UI_PANEL_HEIGHT: 50,
  
  BRICK_ROWS: 5,
  BRICK_COLS: 8,
  BRICK_HEIGHT: 0.03,
  BRICK_PADDING: 5,
  BRICK_OFFSET_TOP: 70,
  BRICK_OFFSET_X: 0.05,
  BRICK_TYPES: [
    { color: 0x0000FF, points: 1 },
    { color: 0xFF0000, points: 2 },
    { color: 0x00FF00, points: 3 },
  ],
  
  PLAY_ZONE_START: 0.65,
  PLAY_ZONE_END: 0.88,
}

export const SCENE_CONFIG = {
  MOBILE: {
    MAX_WIDTH: 450,
    MAX_HEIGHT: 2000,
  },
  DESKTOP: {
    MAX_WIDTH: 600,
    MAX_HEIGHT: 800,
  },
  MOBILE_BREAKPOINT: 768,
  MOBILE_SCREEN_USAGE: 1.0,
  DESKTOP_SCREEN_USAGE: 0.95,
}
